import re

from dataclasses import dataclass

import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
)

from adaptive_agentic_rag.generation.context_builder import (
    BuiltContext,
)

from adaptive_agentic_rag.generation.prompts import (
    build_grounded_messages,
)

from adaptive_agentic_rag.generation.claim_grounder import (
    ClaimGrounder,
)

from adaptive_agentic_rag.generation.relevance_filter import (
    ClaimRelevanceFilter,
)

from adaptive_agentic_rag.generation.citation import (
    validate_citations,
)

from adaptive_agentic_rag.generation.relation_aware_answer_resolver import (
    RelationAwareAnswerResolver,
    RelationResolution,
)

from adaptive_agentic_rag.generation.structured_conclusion_verifier import (
    StructuredConclusionVerifier,
    StructuredVerificationResult,
)


DEFAULT_MODEL = (
    "Qwen/Qwen2.5-1.5B-Instruct"
)


ABSTENTION_MESSAGE = (
    "I don't have enough evidence in the "
    "provided sources to answer reliably."
)


GROUNDING_FAILURE_MESSAGE = (
    "I couldn't find enough supported and relevant claims "
    "in the retrieved evidence to answer reliably."
)


INSUFFICIENT_TOKEN = (
    "INSUFFICIENT_EVIDENCE"
)


# ============================================================
# Structured generation
# ============================================================

@dataclass
class DraftFact:

    text: str

    # --------------------------------------------------------
    # Generator never chooses trusted citations.
    #
    # Grounder assigns citation IDs after verification.
    # --------------------------------------------------------

    citation_id: int | None = None


@dataclass
class ParsedDraft:

    direct_answer: str | None

    evidence_facts: list[DraftFact]


    @property
    def evidence_claims(
        self,
    ) -> list[str]:

        return [
            fact.text
            for fact
            in self.evidence_facts
        ]


# ============================================================
# Final result
# ============================================================

@dataclass
class GenerationResult:

    answer: str

    raw_answer: str | None

    # --------------------------------------------------------
    # Final direct answer after deterministic relation
    # resolution, if the resolver safely applies.
    # --------------------------------------------------------

    direct_answer: str | None

    # --------------------------------------------------------
    # Original DIRECT_ANSWER generated by Qwen.
    #
    # This preserves ablation / diagnostic visibility.
    # --------------------------------------------------------

    draft_direct_answer: str | None

    abstained: bool

    cited_ids: list[int]

    invalid_citation_ids: list[int]

    citation_valid: bool

    model_name: str | None

    draft_claims: int

    supported_claims: int

    unsupported_claims: int

    relevant_claims: int

    filtered_irrelevant_claims: int


class GroundedGenerator:

    def __init__(
        self,
        reranker,
        model_name: str = DEFAULT_MODEL,
        device: str | None = None,
        max_relevant_claims: int = 2,
    ):

        self.model_name = (
            model_name
        )


        self.reranker = (
            reranker
        )


        if device is None:

            device = (
                "cuda"
                if torch.cuda.is_available()
                else "cpu"
            )


        self.device = (
            device
        )


        # ====================================================
        # Lazy-loaded heavy components
        # ====================================================

        self.tokenizer = None

        self.model = None

        self.claim_grounder = None


        # ====================================================
        # Relevance filtering
        #
        # Keep frozen global top-2 behavior.
        # ====================================================

        self.relevance_filter = (
            ClaimRelevanceFilter(
                reranker=
                    reranker,

                max_relevant_claims=
                    max_relevant_claims,
            )
        )


        # ====================================================
        # Conservative deterministic answer resolver.
        #
        # No model.
        # No embedding threshold.
        # No second generation pass.
        # ====================================================

        self.relation_resolver = (
            RelationAwareAnswerResolver()
        )

        self.structured_verifier = (
            StructuredConclusionVerifier(
                relation_resolver=
                    self.relation_resolver,
            )
        )


    # ========================================================
    # Generator loading
    # ========================================================

    def _load_generator(
        self,
    ):

        if (
            self.model is not None
            and
            self.tokenizer is not None
        ):

            return


        print(
            f"Loading generator: "
            f"{self.model_name}"
        )


        self.tokenizer = (
            AutoTokenizer.from_pretrained(
                self.model_name
            )
        )


        dtype = (
            torch.float16
            if self.device == "cuda"
            else torch.float32
        )


        self.model = (
            AutoModelForCausalLM.from_pretrained(
                self.model_name,
                dtype=dtype,
            )
        )


        self.model.to(
            self.device
        )


        self.model.eval()


    # ========================================================
    # Grounder loading
    # ========================================================

    def _load_claim_grounder(
        self,
    ):

        if (
            self.claim_grounder
            is not None
        ):

            return


        self.claim_grounder = (
            ClaimGrounder(
                reranker=
                    self.reranker,

                device=
                    self.device,

                max_candidate_units=
                    6,
            )
        )


    # ========================================================
    # Generate structured draft
    # ========================================================

    def _generate_draft(
        self,
        query: str,
        context: BuiltContext,
        max_new_tokens: int,
    ) -> str:

        messages = (
            build_grounded_messages(
                query=
                    query,

                context=
                    context,
            )
        )


        prompt = (
            self.tokenizer
            .apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        )


        inputs = (
            self.tokenizer(
                prompt,
                return_tensors="pt",
            )
        )


        inputs = {
            key:
                value.to(
                    self.device
                )

            for (
                key,
                value,
            ) in inputs.items()
        }


        input_length = (
            inputs[
                "input_ids"
            ].shape[
                1
            ]
        )


        with torch.no_grad():

            output = (
                self.model.generate(
                    **inputs,

                    max_new_tokens=
                        max_new_tokens,

                    do_sample=
                        False,

                    pad_token_id=(
                        self.tokenizer
                        .eos_token_id
                    ),
                )
            )


        generated_tokens = (
            output[
                0
            ][
                input_length:
            ]
        )


        return (
            self.tokenizer.decode(
                generated_tokens,
                skip_special_tokens=True,
            )
            .strip()
        )


    # ========================================================
    # Generated-text normalization
    # ========================================================

    @staticmethod
    def _clean_generated_text(
        text: str,
    ) -> str:

        text = (
            text
            or ""
        )


        # Generator is not trusted to assign citations.

        text = re.sub(
            r"\[\d+\]",
            "",
            text,
        )


        text = re.sub(
            r"\s+",
            " ",
            text,
        )


        return (
            text.strip()
        )


    # ========================================================
    # Explicit model abstention
    # ========================================================

    @staticmethod
    def _is_insufficient_answer(
        answer: str | None,
    ) -> bool:

        if not answer:

            return False


        normalized = (
            answer
            .strip()
            .strip(
                " .,:;!?"
            )
            .upper()
        )


        normalized = re.sub(
            r"[\s_-]+",
            "_",
            normalized,
        )


        return normalized in {
            "INSUFFICIENT_EVIDENCE",
            "INSUFFICIENT",
        }


    # ========================================================
    # Parse:
    #
    # DIRECT_ANSWER: ...
    #
    # FACTS:
    # - ...
    # - ...
    # ========================================================

    @classmethod
    def _parse_draft(
        cls,
        raw_answer: str,
    ) -> ParsedDraft:

        direct_answer = None

        evidence_facts = []

        inside_facts = False


        for raw_line in (
            raw_answer.splitlines()
        ):

            line = (
                raw_line.strip()
            )


            if not line:

                continue


            # =================================================
            # DIRECT_ANSWER
            #
            # DRAFT_ANSWER remains accepted for compatibility.
            # =================================================

            direct_match = re.match(
                (
                    r"^(?:DIRECT_ANSWER|DRAFT_ANSWER)"
                    r"\s*:\s*(.*)$"
                ),
                line,
                flags=re.IGNORECASE,
            )


            if direct_match:

                value = (
                    cls._clean_generated_text(
                        direct_match.group(
                            1
                        )
                    )
                )


                if value:

                    direct_answer = (
                        value
                    )


                inside_facts = False

                continue


            # =================================================
            # FACTS header
            # =================================================

            facts_match = re.match(
                r"^FACTS\s*:\s*(.*)$",
                line,
                flags=re.IGNORECASE,
            )


            if facts_match:

                inside_facts = True


                inline_fact = (
                    cls._clean_generated_text(
                        facts_match.group(
                            1
                        )
                    )
                )


                if inline_fact:

                    evidence_facts.append(
                        DraftFact(
                            text=
                                inline_fact,
                        )
                    )


                continue


            # =================================================
            # Bullet fact
            # =================================================

            bullet_match = re.match(
                r"^[-*•]\s*(.+)$",
                line,
            )


            if bullet_match:

                fact = (
                    cls._clean_generated_text(
                        bullet_match.group(
                            1
                        )
                    )
                )


                if fact:

                    evidence_facts.append(
                        DraftFact(
                            text=
                                fact,
                        )
                    )


                continue


            # =================================================
            # Small-model fallback:
            #
            # after FACTS: accept standalone lines.
            # =================================================

            if inside_facts:

                fact = (
                    cls._clean_generated_text(
                        line
                    )
                )


                if fact:

                    evidence_facts.append(
                        DraftFact(
                            text=
                                fact,
                        )
                    )


        # ====================================================
        # Stable deduplication
        # ====================================================

        unique = []

        seen = set()


        for fact in (
            evidence_facts
        ):

            key = (
                fact.text
            )


            if key in seen:

                continue


            seen.add(
                key
            )


            unique.append(
                fact
            )


        return ParsedDraft(
            direct_answer=
                direct_answer,

            evidence_facts=
                unique,
        )


    # ========================================================
    # Parsed facts → Grounder input
    # ========================================================

    @staticmethod
    def _render_claims_for_grounding(
        facts: list[DraftFact],
    ) -> str:

        return "\n".join(
            (
                f"- {fact.text}"
            )

            for fact
            in facts
        )


    # ========================================================
    # Citation → context metadata
    #
    # Diagnostic helper only.
    # ========================================================

    @staticmethod
    def _context_item_for_citation(
        context: BuiltContext,
        citation_id: int | None,
    ):

        if citation_id is None:

            return None


        for item in context.items:

            if (
                item.citation_id
                ==
                citation_id
            ):

                return item


        return None


    # ========================================================
    # Grounding diagnostics
    # ========================================================

    def _print_grounding_diagnostics(
        self,
        *,
        grounded_claims,
        context: BuiltContext,
    ) -> None:

        print(
            "\n===== CLAIM GROUNDING ====="
        )


        print(
            "Supported claims:",
            grounded_claims.supported_count,
        )


        print(
            "Unsupported claims:",
            grounded_claims.unsupported_count,
        )


        for index, claim in enumerate(
            grounded_claims.claims,
            start=1,
        ):

            item = (
                self._context_item_for_citation(
                    context=
                        context,

                    citation_id=
                        claim.citation_id,
                )
            )


            source = (
                getattr(
                    item,
                    "source",
                    None,
                )
                if item is not None
                else None
            )


            title = (
                getattr(
                    item,
                    "title",
                    None,
                )
                if item is not None
                else None
            )


            print(
                "\n"
                +
                "-" * 80
            )


            print(
                f"GROUND CLAIM {index}"
            )


            print(
                "-" * 80
            )


            print(
                "Claim:",
                claim.claim,
            )


            print(
                "Supported:",
                claim.supported,
            )


            print(
                "Citation ID:",
                claim.citation_id,
            )


            print(
                "Citation source:",
                source,
            )


            print(
                "Citation title:",
                title,
            )


            print(
                "NLI label:",
                claim.label,
            )


            print(
                "Entailment score:",
                claim.entailment_score,
            )


            print(
                "Evidence relevance score:",
                claim.evidence_relevance_score,
            )


            print(
                "Premise mode:",
                claim.premise_mode,
            )


            print(
                "Supporting text:"
            )


            print(
                claim.supporting_text
            )


    # ========================================================
    # Relation-aware direct-answer resolution
    #
    # IMPORTANT:
    #
    # Resolver receives ONLY:
    #
    #   supported
    #   +
    #   query-relevant
    #
    # claims.
    #
    # Raw Qwen facts never enter this step directly.
    # ========================================================

    def _resolve_direct_answer(
        self,
        *,
        query: str,
        draft_direct_answer: str,
        relevant_claims,
        context: BuiltContext | None = None,
    ) -> tuple[
        str,
        RelationResolution,
        RelationResolution | StructuredVerificationResult,
    ]:

        verifier = getattr(
            self,
            "structured_verifier",
            None,
        )

        resolver = getattr(
            self,
            "relation_resolver",
            None,
        )


        # ----------------------------------------------------
        # Backward compatibility for tests that construct
        # GroundedGenerator via object.__new__().
        # ----------------------------------------------------

        if resolver is None:

            resolver = (
                RelationAwareAnswerResolver()
            )


            self.relation_resolver = (
                resolver
            )

        if verifier is None:
            verifier = (
                StructuredConclusionVerifier(
                    relation_resolver=
                        resolver,
                )
            )
            self.structured_verifier = (
                verifier
            )

        facts = [
            claim.claim

            for claim
            in relevant_claims
        ]

        covered_sources = []
        all_context_sources = []
        if context is not None and getattr(context, "items", None):
            citation_to_source = {
                item.citation_id: item.source
                for item
                in context.items
                if getattr(item, "source", None)
            }
            seen = set()
            for claim in relevant_claims:
                src = citation_to_source.get(
                    getattr(claim, "citation_id", None)
                )
                if src and src not in seen:
                    seen.add(src)
                    covered_sources.append(src)

        resolution = (
            resolver.resolve(
            seen_ctx = set()
            for item in context.items:
                src = getattr(item, "source", None)
                if src and src not in seen_ctx:
                    seen_ctx.add(src)
                    all_context_sources.append(src)

        verification = (
            verifier.verify(
                query=
                    query,

                facts=
                draft_direct_answer=
                    draft_direct_answer,
                grounded_facts=
                    facts,
                covered_sources=
                    covered_sources,
                all_context_sources=
                    all_context_sources,
            )
        )


        if (
            resolution.applied
            verification.applied
            and
            resolution.resolved_answer
            verification.resolved_answer
        ):

            return (
                resolution.resolved_answer,
                resolution,
                verification.resolved_answer,
                verification,
            )


        return (
            draft_direct_answer,
            resolution,
            verification,
        )


    # ========================================================
    # Final answer construction
    # ========================================================

    @staticmethod
    def _build_grounded_answer(
        direct_answer: str,
        relevant_claims,
    ) -> str:

        lines = []


        citation_ids = list(
            dict.fromkeys(
                (
                    claim.citation_id
                )

                for claim
                in relevant_claims

                if (
                    claim.citation_id
                    is not None
                )
            )
        )


        citation_suffix = "".join(
            (
                f"[{citation_id}]"
            )

            for citation_id
            in citation_ids
        )


        direct_line = (
            direct_answer.strip()
        )


        if citation_suffix:

            direct_line += (
                f" {citation_suffix}"
            )


        lines.append(
            direct_line
        )


        for claim in (
            relevant_claims
        ):

            lines.append(
                (
                    f"- {claim.claim} "
                    f"[{claim.citation_id}]"
                )
            )


        return "\n".join(
            lines
        )


    # ========================================================
    # Main generation pipeline
    # ========================================================

    def generate(
        self,
        query: str,
        context: BuiltContext,
        evidence_sufficient: bool,
        max_new_tokens: int = 220,
    ) -> GenerationResult:

        # ====================================================
        # Gate 1:
        # Evidence Gate rejected evidence.
        #
        # Do NOT load Qwen.
        # ====================================================

        if not evidence_sufficient:

            return GenerationResult(
                answer=
                    ABSTENTION_MESSAGE,

                raw_answer=
                    None,

                direct_answer=
                    None,

                draft_direct_answer=
                    None,

                abstained=
                    True,

                cited_ids=
                    [],

                invalid_citation_ids=
                    [],

                citation_valid=
                    True,

                model_name=
                    None,

                draft_claims=
                    0,

                supported_claims=
                    0,

                unsupported_claims=
                    0,

                relevant_claims=
                    0,

                filtered_irrelevant_claims=
                    0,
            )


        # ====================================================
        # Step 1:
        # Structured single-pass generation
        # ====================================================

        self._load_generator()


        raw_answer = (
            self._generate_draft(
                query=
                    query,

                context=
                    context,

                max_new_tokens=
                    max_new_tokens,
            )
        )


        print(
            "\n===== RAW GENERATION ====="
        )


        print(
            raw_answer
        )


        # ====================================================
        # Step 2:
        # Parse answer and evidence facts separately.
        # ====================================================

        parsed = (
            self._parse_draft(
                raw_answer
            )
        )


        print(
            "\n===== PARSED DRAFT ====="
        )


        print(
            "Direct answer:",
            parsed.direct_answer,
        )


        print(
            "Evidence facts:",
            len(
                parsed.evidence_facts
            ),
        )


        for fact in (
            parsed.evidence_facts
        ):

            print(
                "FACT:",
                fact.text,
            )


        # ====================================================
        # Gate 2:
        # Generator explicitly abstained.
        # ====================================================

        if (
            self._is_insufficient_answer(
                parsed.direct_answer
            )
        ):

            return GenerationResult(
                answer=
                    ABSTENTION_MESSAGE,

                raw_answer=
                    raw_answer,

                direct_answer=
                    None,

                draft_direct_answer=
                    parsed.direct_answer,

                abstained=
                    True,

                cited_ids=
                    [],

                invalid_citation_ids=
                    [],

                citation_valid=
                    True,

                model_name=
                    self.model_name,

                draft_claims=
                    len(
                        parsed.evidence_facts
                    ),

                supported_claims=
                    0,

                unsupported_claims=
                    0,

                relevant_claims=
                    0,

                filtered_irrelevant_claims=
                    0,
            )


        # ====================================================
        # Gate 3:
        # Structured output contract failed.
        # ====================================================

        if not parsed.direct_answer:

            return GenerationResult(
                answer=
                    GROUNDING_FAILURE_MESSAGE,

                raw_answer=
                    raw_answer,

                direct_answer=
                    None,

                draft_direct_answer=
                    None,

                abstained=
                    True,

                cited_ids=
                    [],

                invalid_citation_ids=
                    [],

                citation_valid=
                    False,

                model_name=
                    self.model_name,

                draft_claims=
                    len(
                        parsed.evidence_facts
                    ),

                supported_claims=
                    0,

                unsupported_claims=
                    0,

                relevant_claims=
                    0,

                filtered_irrelevant_claims=
                    0,
            )


        if not (
            parsed.evidence_facts
        ):

            return GenerationResult(
                answer=
                    GROUNDING_FAILURE_MESSAGE,

                raw_answer=
                    raw_answer,

                direct_answer=
                    parsed.direct_answer,

                draft_direct_answer=
                    parsed.direct_answer,

                abstained=
                    True,

                cited_ids=
                    [],

                invalid_citation_ids=
                    [],

                citation_valid=
                    False,

                model_name=
                    self.model_name,

                draft_claims=
                    0,

                supported_claims=
                    0,

                unsupported_claims=
                    0,

                relevant_claims=
                    0,

                filtered_irrelevant_claims=
                    0,
            )


        # ====================================================
        # Step 3:
        # Ground FACTS only.
        #
        # DIRECT_ANSWER itself does not enter NLI.
        # ====================================================

        self._load_claim_grounder()


        grounding_input = (
            self._render_claims_for_grounding(
                parsed.evidence_facts
            )
        )


        grounded_claims = (
            self.claim_grounder.ground(
                answer=
                    grounding_input,

                context=
                    context,
            )
        )


        self._print_grounding_diagnostics(
            grounded_claims=
                grounded_claims,

            context=
                context,
        )


        # ====================================================
        # Gate 4:
        # No evidence fact survived grounding.
        # ====================================================

        if (
            grounded_claims.supported_count
            ==
            0
        ):

            return GenerationResult(
                answer=
                    GROUNDING_FAILURE_MESSAGE,

                raw_answer=
                    raw_answer,

                direct_answer=
                    parsed.direct_answer,

                draft_direct_answer=
                    parsed.direct_answer,

                abstained=
                    True,

                cited_ids=
                    [],

                invalid_citation_ids=
                    [],

                citation_valid=
                    False,

                model_name=
                    self.model_name,

                draft_claims=
                    len(
                        parsed.evidence_facts
                    ),

                supported_claims=
                    0,

                unsupported_claims=(
                    grounded_claims
                    .unsupported_count
                ),

                relevant_claims=
                    0,

                filtered_irrelevant_claims=
                    0,
            )


        # ====================================================
        # Step 4:
        # Query relevance over supported facts.
        # ====================================================

        relevance_result = (
            self.relevance_filter.filter(
                query=
                    query,

                grounded_claims=
                    grounded_claims,

                context=
                    context,
            )
        )


        print(
            "\n===== CLAIM RELEVANCE ====="
        )


        print(
            "Relevant claims:",
            len(
                relevance_result
                .relevant_claims
            ),
        )


        print(
            "Filtered irrelevant claims:",
            len(
                relevance_result
                .filtered_claims
            ),
        )


        for claim in (
            relevance_result
            .relevant_claims
        ):

            print(
                "KEEP:",
                claim.relevance_score,
                claim.claim,
            )


        for claim in (
            relevance_result
            .filtered_claims
        ):

            print(
                "FILTER:",
                claim.relevance_score,
                claim.claim,
            )


        # ====================================================
        # Gate 5:
        # No supported fact is relevant to query.
        # ====================================================

        if not (
            relevance_result
            .relevant_claims
        ):

            return GenerationResult(
                answer=
                    GROUNDING_FAILURE_MESSAGE,

                raw_answer=
                    raw_answer,

                direct_answer=
                    parsed.direct_answer,

                draft_direct_answer=
                    parsed.direct_answer,

                abstained=
                    True,

                cited_ids=
                    [],

                invalid_citation_ids=
                    [],

                citation_valid=
                    False,

                model_name=
                    self.model_name,

                draft_claims=
                    len(
                        parsed.evidence_facts
                    ),

                supported_claims=(
                    grounded_claims
                    .supported_count
                ),

                unsupported_claims=(
                    grounded_claims
                    .unsupported_count
                ),

                relevant_claims=
                    0,

                filtered_irrelevant_claims=(
                    len(
                        relevance_result
                        .filtered_claims
                    )
                ),
            )


        # ====================================================
        # Step 5:
        # Conservative relation-aware answer resolution.
        #
        # Input:
        #
        # ONLY grounded + relevant facts.
        #
        # No raw facts.
        # No unsupported facts.
        #
        # If no safe rule applies, Qwen DIRECT_ANSWER is
        # preserved unchanged.
        # ====================================================

        (
            resolved_direct_answer,
            relation_resolution,
        ) = (
            self._resolve_direct_answer(
                query=
                    query,

                draft_direct_answer=
                    parsed.direct_answer,

                relevant_claims=(
                    relevance_result
                    .relevant_claims
                ),

                context=
                    context,
            )
        )


        print(
            "\n===== ANSWER RELATION RESOLUTION ====="
        )


        print(
            "Applied:",
            relation_resolution.applied,
            getattr(
                relation_resolution,
                "applied",
                False,
            ),
        )


        print(
            "Relation type:",
            relation_resolution.relation_type,
            "Relation / Mechanism:",
            getattr(
                relation_resolution,
                "applied_mechanism",
                getattr(
                    relation_resolution,
                    "relation_type",
                    "none",
                ),
            ),
        )


        print(
            "Requested polarity:",
            relation_resolution.requested_polarity,
            getattr(
                relation_resolution,
                "requested_polarity",
                getattr(
                    getattr(
                        relation_resolution,
                        "relation_resolution",
                        None,
                    ),
                    "requested_polarity",
                    None,
                ),
            ),
        )


        print(
            "Draft direct answer:",
            parsed.direct_answer,
        )


        print(
            "Resolved direct answer:",
            resolved_direct_answer,
        )


        print(
            "Reason:",
            relation_resolution.reason,
            getattr(
                relation_resolution,
                "reason",
                "",
            ),
        )


        # ====================================================
        # Step 6:
        # Final direct answer + verified facts.
        # ====================================================

        final_answer = (
            self._build_grounded_answer(
                direct_answer=
                    resolved_direct_answer,

                relevant_claims=(
                    relevance_result
                    .relevant_claims
                ),
            )
        )


        # ====================================================
        # Step 7:
        # Citation validation
        # ====================================================

        citation_validation = (
            validate_citations(
                answer=
                    final_answer,

                context=
                    context,
            )
        )


        if not (
            citation_validation.valid
        ):

            return GenerationResult(
                answer=
                    GROUNDING_FAILURE_MESSAGE,

                raw_answer=
                    raw_answer,

                direct_answer=
                    resolved_direct_answer,

                draft_direct_answer=
                    parsed.direct_answer,

                abstained=
                    True,

                cited_ids=(
                    citation_validation
                    .cited_ids
                ),

                invalid_citation_ids=(
                    citation_validation
                    .invalid_ids
                ),

                citation_valid=
                    False,

                model_name=
                    self.model_name,

                draft_claims=
                    len(
                        parsed.evidence_facts
                    ),

                supported_claims=(
                    grounded_claims
                    .supported_count
                ),

                unsupported_claims=(
                    grounded_claims
                    .unsupported_count
                ),

                relevant_claims=(
                    len(
                        relevance_result
                        .relevant_claims
                    )
                ),

                filtered_irrelevant_claims=(
                    len(
                        relevance_result
                        .filtered_claims
                    )
                ),
            )


        # ====================================================
        # Success
        # ====================================================

        return GenerationResult(
            answer=
                final_answer,

            raw_answer=
                raw_answer,

            # ------------------------------------------------
            # Final answer after safe deterministic resolution.
            # ------------------------------------------------

            direct_answer=
                resolved_direct_answer,

            # ------------------------------------------------
            # Preserve raw Qwen synthesis for ablations.
            # ------------------------------------------------

            draft_direct_answer=
                parsed.direct_answer,

            abstained=
                False,

            cited_ids=(
                citation_validation
                .cited_ids
            ),

            invalid_citation_ids=(
                citation_validation
                .invalid_ids
            ),

            citation_valid=
                True,

            model_name=
                self.model_name,

            draft_claims=
                len(
                    parsed.evidence_facts
                ),

            supported_claims=(
                grounded_claims
                .supported_count
            ),

            unsupported_claims=(
                grounded_claims
                .unsupported_count
            ),

            relevant_claims=(
                len(
                    relevance_result
                    .relevant_claims
                )
            ),

            filtered_irrelevant_claims=(
                len(
                    relevance_result
                    .filtered_claims
                )
            ),
        )